---
- name: Create a virtual machine on ESXi
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: create vm
    vmware_guest:
      hostname: '{{ hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      validate_certs: no
      folder: /Datacenter/vm/
      datacenter: Datacenter-1
      name: test_vm_0001
      state: poweredoff
      guest_id: centos64Guest
      # This is hostname of particular ESXi server on which user wants VM to be deployed
      esxi_hostname: '{{ esxi_ip }}'
      disk:
      - size_gb: 10
        type: thin
        datastore: '{{ datastore_name }}'
      hardware:
        memory_mb: 1024
        num_cpus: 2
        scsi: paravirtual
      networks:
      - name: '{{ network_ip }}'
        mac: aa:bb:cc:dd:ee:ff
        ip: '{{ network_ip }}'
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy_vm
