# Run this playbook by executiong the following command:
#
# ansible-playbook --ask-become-pass install-docker.yaml
#
---
- name: Install docker-ce
  hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Purge existing packages
      apt:  
        purge: yes
        state: absent
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
    
    - name: Install prerequisites
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
    
    - name: Add docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        validate_certs: yes

    - name: Add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker-ce

    - name: Install docker-ce
      apt:
        update_cache: yes
        name:
        - docker-ce 
        - docker-ce-cli
        - containerd.io

    - name: Add group docker
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user: 
        name: racoon
        group: racoon
        append: yes
        groups:
          - docker

    - name: Allow user of the docker group to use docker
      file:
        path: /var/run/docker.sock
        group: docker
        mode: '0660'

    - name: Enable the docker service
      systemd:
        name: docker.service
        daemon_reload: yes
        enabled: yes
        state: restarted
